{"name": "test_login_with_invalid_credentials", "status": "passed", "attachments": [{"name": "log", "source": "187c6b93-6165-43ab-85cf-954c1c44607c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0d6e3cdb-5ebd-42a7-94cd-851d5a1c7ac9-attachment.txt", "type": "text/plain"}], "start": 1650957444474, "stop": 1650957446098, "uuid": "f720542e-e2d6-470c-954a-5670148382a8", "historyId": "ebecc3f339f062283bbbc5072ccbf91f", "testCaseId": "5434307b06cd1f4cc4ff0b511533f25e", "fullName": "tests.test_login.TestPageFeature#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestPageFeature"}, {"name": "host", "value": "aszton"}, {"name": "thread", "value": "35925-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}